version: '3.8'

services:
  app:
    image: vavra/project-shared_app
    container_name: project-shared_app
    build:
      context: ./
      dockerfile: ./services/app/Dockerfile
      args:
        NODE_VERSION: 14.4
    depends_on:
      - server
    ports:
      - '3000:3000'

  server:
    image: vavra/project-shared_server
    container_name: project-shared_server
    build:
      context: ./
      dockerfile: ./services/server/Dockerfile
      args:
        NODE_VERSION: 14.4
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      STORAGE_PASSWORD: ${STORAGE_PASSWORD}
      SESSION_SECRET: ${SESSION_SECRET}
      APP_URL: ${APP_URL}
    depends_on:
      - db
    ports:
      - '4000:4000'

  db:
    image: postgres:12
    container_name: project-shared_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    ports:
      - '5432:5432'

  storage:
    image: redis:6
    container_name: project-shared_storage
    command: redis-server --requirepass ${STORAGE_PASSWORD}
    volumes:
      - type: volume
        source: storage-data
        target: /var/lib/redis
    ports:
      - '6379:6397'

volumes:
  db-data:
    name: project-shared_db-data
  storage-data:
    name: project-shared_storage-data
