version: '3.8'

services:
  shared:
    image: vavra/dev_project-shared_shared
    container_name: dev_project-shared_shared
    build:
      context: ./
      dockerfile: ./packages/shared/Dockerfile.dev
      args:
        NODE_VERSION: 13.14
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/services

  client:
    image: vavra/dev_project-shared_client
    container_name: dev_project-shared_client
    user: 1000:1000
    build:
      context: ./
      dockerfile: ./services/client/Dockerfile.dev
      args:
        NODE_VERSION: 13.14
    environment:
      GQL_NETWORK_URL: ${GQL_NETWORK_URL}
      GQL_PUBLIC_URL: ${GQL_PUBLIC_URL}
    depends_on:
      - server
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/services/server

  server:
    image: vavra/dev_project-shared_server
    container_name: dev_project-shared_server
    build:
      context: ./
      dockerfile: ./services/server/Dockerfile.dev
      args:
        NODE_VERSION: 13.14
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      STORE_PASSWORD: ${STORE_PASSWORD}
      SESSION_SECRET: ${SESSION_SECRET}
      CLIENT_URL: ${CLIENT_URL}
    depends_on:
      - db
      - store
      - shared
    ports:
      - '4000:4000'
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/services/client
    restart: always

  db:
    image: postgres:12
    container_name: dev_project-shared_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    ports:
      - '5432:5432'

  store:
    image: redis:6
    container_name: dev_project-shared_store
    command: redis-server --requirepass ${STORE_PASSWORD}
    volumes:
      - type: volume
        source: store-data
        target: /var/lib/redis
    ports:
      - '6379:6397'

volumes:
  db-data:
    name: project-shared_db-data
  store-data:
    name: project-shared_store-data
