version: "3.8"

services: 
  server:
    container_name: project-shared_server
    image: vavra/project-shared_server
    build: 
      context: ./
      dockerfile: ./services/server/Dockerfile
    ports: 
      - "5000:5000"