version: '3.8'

services:
  shared:
    image: vavra/dev_project-shared_shared
    container_name: dev_project-shared_shared
    build:
      context: ./
      dockerfile: ./packages/shared/Dockerfile.dev
      args:
        NODE_VERSION: 13.14
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/services

  app:
    image: vavra/dev_project-shared_app
    container_name: dev_project-shared_app
    build:
      context: ./
      dockerfile: ./services/app/Dockerfile.dev
      args:
        NODE_VERSION: 13.14
    depends_on:
      - server
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/services/server

  server:
    image: vavra/dev_project-shared_server
    container_name: dev_project-shared_server
    build:
      context: ./
      dockerfile: ./services/server/Dockerfile.dev
      args:
        NODE_VERSION: 13.14
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      STORAGE_PASSWORD: ${STORAGE_PASSWORD}
      SESSION_SECRET: ${SESSION_SECRET}
      APP_URL: ${APP_URL}
    depends_on:
      - shared
      - db
    ports:
      - '4000:4000'
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/services/app

  db:
    image: postgres:12
    container_name: dev_project-shared_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    ports:
      - '5432:5432'

  storage:
    image: redis:6
    container_name: dev_project-shared_storage
    command: redis-server --requirepass ${STORAGE_PASSWORD}
    volumes:
      - type: volume
        source: storage-data
        target: /var/lib/redis
    ports:
      - '6379:6397'

volumes:
  db-data:
    name: project-shared_db-data
  storage-data:
    name: project-shared_storage-data
